# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/mnt/vault1/mfaroo19/quantum-net-final/latency-opt/lat-opt-classifer/lat-opt-classifier.runs/synth_1/nn_classifier_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu49dr-ffvf1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/lat-opt-classifer/lat-opt-classifier.cache/wt [current_project]
set_property parent.project_path /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/lat-opt-classifer/lat-opt-classifier.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets [current_fileset]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/sum_signed.sv
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/readout_ip.sv
}
read_verilog -library xil_defaultlib {
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N0.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N1.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N10.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N100.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N101.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N102.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N103.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N104.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N105.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N106.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N107.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N108.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N109.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N11.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N110.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N111.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N112.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N113.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N114.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N115.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N116.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N117.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N118.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N119.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N12.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N120.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N121.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N122.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N123.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N124.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N125.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N126.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N127.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N128.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N129.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N13.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N130.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N131.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N132.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N133.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N134.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N135.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N136.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N137.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N138.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N139.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N14.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N140.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N141.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N142.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N143.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N144.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N15.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N16.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N17.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N18.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N19.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N2.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N20.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N21.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N22.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N23.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N24.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N25.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N26.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N27.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N28.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N29.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N3.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N30.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N31.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N32.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N33.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N34.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N35.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N36.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N37.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N38.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N39.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N4.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N40.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N41.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N42.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N43.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N44.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N45.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N46.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N47.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N48.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N49.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N5.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N50.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N51.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N52.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N53.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N54.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N55.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N56.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N57.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N58.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N59.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N6.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N60.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N61.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N62.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N63.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N64.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N65.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N66.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N67.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N68.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N69.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N7.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N70.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N71.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N72.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N73.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N74.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N75.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N76.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N77.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N78.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N79.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N8.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N80.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N81.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N82.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N83.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N84.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N85.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N86.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N87.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N88.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N89.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N9.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N90.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N91.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N92.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N93.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N94.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N95.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N96.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N97.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N98.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer0_N99.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N0.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N1.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N10.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N11.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N12.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N13.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N14.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N15.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N16.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N17.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N18.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N19.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N2.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N20.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N21.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N22.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N23.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N24.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N25.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N26.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N27.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N28.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N29.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N3.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N30.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N31.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N32.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N33.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N34.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N4.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N5.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N6.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N7.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N8.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer1_N9.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N0.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N1.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N10.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N11.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N12.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N13.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N14.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N2.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N3.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N4.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N5.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N6.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N7.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N8.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer2_N9.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer3.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/layer3_N0.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/logicnet.v
  /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/logicnets/myreg.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/constraints.xdc
set_property used_in_implementation false [get_files /mnt/vault1/mfaroo19/quantum-net-final/latency-opt/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top nn_classifier_wrapper -part xczu49dr-ffvf1760-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nn_classifier_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nn_classifier_wrapper_utilization_synth.rpt -pb nn_classifier_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
