# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-2457905-en4228283l/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu7ev-ffvc1156-2-e
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets {
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/readout_ip.sv
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/sum_signed.sv
    }
      rt::read_verilog -include /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets {
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N12.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N76.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N2.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N7.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N12.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N5.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N139.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N135.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N7.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N37.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N115.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N90.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N124.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N35.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N54.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N43.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N118.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N10.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N13.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N120.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N11.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N45.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N11.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N95.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N85.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N19.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N2.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N3.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N4.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N17.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N1.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N65.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/logicnet.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N143.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N62.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N103.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N24.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N104.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N8.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N18.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N100.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N2.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N125.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N9.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N63.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N91.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N49.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N88.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N107.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N44.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N84.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N26.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N29.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N20.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N52.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N41.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N14.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N26.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N114.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N21.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N69.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N98.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N24.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N68.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N39.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N93.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N5.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N11.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N6.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N50.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N89.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N1.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N27.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N117.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N66.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N39.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N82.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N70.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N6.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N6.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N10.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N0.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N8.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N40.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N108.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N8.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N25.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N48.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/myreg.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N32.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N72.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N58.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N13.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N113.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N80.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N0.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N34.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N4.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N25.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N7.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N77.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N111.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N133.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N28.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N23.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N14.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N102.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N36.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N15.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N75.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N30.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N78.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N27.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N35.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N57.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N36.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N122.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N28.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N142.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N20.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N83.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N96.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N18.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N5.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N31.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N130.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N15.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N42.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N138.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N116.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N112.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N47.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N22.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N16.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N127.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N110.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N21.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N134.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N31.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N1.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N3.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer3.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N3.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N140.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N29.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N61.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N9.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N60.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N121.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N94.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N46.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer3_N0.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N81.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N51.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N105.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N19.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N59.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N38.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N86.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N71.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N56.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N126.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N132.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N4.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N34.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N38.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N0.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N144.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N74.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N87.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N37.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N22.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N12.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N17.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N64.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N16.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N97.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N67.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N129.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N79.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N23.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N131.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N123.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N53.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N136.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N33.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N101.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N14.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N106.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N10.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer2_N13.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N141.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N99.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N9.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N73.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N92.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N119.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N33.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N109.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N137.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N30.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer1_N32.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N55.v
      /mnt/vault1/mfaroo19/quantum-net-final/project_1/project_1.srcs/sources_1/new/logicnets/layer0_N128.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-2457905-en4228283l/realtime/nn_classifier_wrapper_synth.xdc
    rt::sdcChecksum
    set rt::top nn_classifier_wrapper
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {./.Xil/Vivado-2457905-en4228283l/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-2457905-en4228283l/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    rt::close_pss_mem_watcher
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
